### ISSUE TITLE
Additional data in flattenTree & Node

### ISSUE THREAD

**Issue by oman21** [dgreene1/react-accessible-treeview#82] opened 2023-02-01 04:58 UTC
it is posible to add additional data ? like i want to add object category_id

const data = [
  { category_id: null, name: "", children: [1, 4, 9, 10, 11], id: 0, parent: null },
  { category_id: 1, name: "src", children: [2, 3], id: 1, parent: 0 },
  { category_id: 2, name: "index.js", id: 2, parent: 1 },
  { category_id: 3,  name: "styles.css", id: 3, parent: 1 },
  { category_id: 4,  name: "node_modules", children: [5, 7], id: 4, parent: 0 },
  { category_id: 5,  name: "react-accessible-treeview", children: [6], id: 5, parent: 4 },
  { category_id: 6,  name: "bundle.js", id: 6, parent: 5 },
  { category_id: 7, name: "react", children: [8], id: 7, parent: 4 },
  { category_id: 8, name: "bundle.js", id: 8, parent: 7 },
  { category_id: 9, name: ".npmignore", id: 9, parent: 0 },
  { category_id: 10, name: "package.json", id: 10, parent: 0 },
  { category_id: 11, name: "webpack.config.js", id: 11, parent: 0 },
];

**Comment by dgreene1** [comment] 2023-02-01 12:54
You should be able to accomplish this with https://dgreene1.github.io/react-accessible-treeview/docs/api#noderenderer

Note to myself: this seems like a duplicate of #70

**Closed as completed by dgreene1** 2023-02-01 12:54 UTC
